const position = { x: 0, y: 0 };

export const initialNodes = [
  {
    id: "CS161",
    type: "input",
    data: { label: "161 - Intro to Computer Science I" },
    position,
    taken: false,
  },
  {
    id: "CS225",
    type: "input",
    data: { label: "225 - Discrete Structures in Computer Science" },
    position,
    taken: false,
  },
  {
    id: "CS391",
    type: "input",
    data: { label: "391 - Social and Ethical Issues in CS" },
    position,
    taken: false,
  },
  {
    id: "CS162",
    data: { label: "162 - Intro to Computer Science II" },
    position,
    taken: false,
  },
  {
    id: "CS271",
    data: { label: "271 - Computer Architecture & Assembly Language" },
    position,
    taken: false,
  },
  {
    id: "CS352",
    data: { label: "352 - Introduction to Usability Engineering" },
    position,
    taken: false,
  },
  {
    id: "CS290",
    data: { label: "290 - Web Development" },
    position,
    taken: false,
  },
  {
    id: "CS261",
    data: { label: "261 - Data Structures" },
    position,
    taken: false,
  },
  {
    id: "CS340",
    data: { label: "340 - Introduction to Databases" },
    position,
    taken: false,
  },
  {
    id: "CS321",
    data: { label: "321 - Intro to Theory of Computation" },
    position,
    taken: false,
  },
  {
    id: "CS325",
    data: { label: "325 - Analysis of Algorithms" },
    position,
    taken: false,
  },
  {
    id: "CS344",
    data: { label: "344 - Operating Systems" },
    position,
    taken: false,
  },
  {
    id: "CS372",
    data: { label: "372 - Intro to Computer Networks" },
    position,
    taken: false,
  },
  {
    id: "CS381",
    data: { label: "381 - Programming Language Fundamentals" },
    position,
    taken: false,
  },
  {
    id: "CS361",
    data: { label: "361 - Software Engineering I" },
    position,
    taken: false,
  },
  {
    id: "CS362",
    data: { label: "362 - Software Engineering II" },
    position,
    taken: false,
  },
  {
    id: "CS427",
    data: { label: "427 - Cryptography" },
    position,
    taken: false,
  },
  {
    id: "CS450",
    data: { label: "450 - Intro to Computer Graphics" },
    position,
    taken: false,
  },
  {
    id: "CS475",
    data: { label: "475 - Intro to Parallel Programming" },
    position,
    taken: false,
  },
  {
    id: "CS493",
    data: { label: "493 - Cloud Application Development" },
    position,
    taken: false,
  },
  {
    id: "CS373",
    data: { label: "373 - Defense Against the Dark Arts" },
    position,
    taken: false,
  },
  {
    id: "CS370",
    data: { label: "370 - Intro to Security" },
    position,
    taken: false,
  },
  {
    id: "CS492",
    data: { label: "492 - Mobile Software Development" },
    position,
    taken: false,
  },
  {
    id: "CS444",
    data: { label: "444 - Advanced Topics" },
    position,
    taken: false,
  },
  {
    id: "CS478",
    data: { label: "478 - Advanced Networks" },
    position,
    taken: false,
  },
  {
    id: "CS467",
    data: { label: "467 - Online Capstone Project" },
    position,
    taken: false,
  },
  {
    id: "CS464",
    data: { label: "464 - Open Source Software" },
    position,
    taken: false,
  },
  {
    id: "CS477",
    data: { label: "477 - Advanced Security" },
    position,
    taken: false,
  },
];

// Edges
export const initialEdges = [
  { id: "eCS161-CS162", source: "CS161", target: "CS162", type: "smoothstep" },
  { id: "eCS161-CS271", source: "CS161", target: "CS271", type: "smoothstep" },
  { id: "eCS161-CS352", source: "CS161", target: "CS352", type: "smoothstep" },
  { id: "eCS162-CS290", source: "CS162", target: "CS290", type: "smoothstep" },
  { id: "eCS162-CS261", source: "CS162", target: "CS261", type: "smoothstep" },
  { id: "eCS290-CS340", source: "CS290", target: "CS340", type: "smoothstep" },
  { id: "eCS261-CS321", source: "CS261", target: "CS321", type: "smoothstep" },
  { id: "eCS225-CS321", source: "CS225", target: "CS321", type: "smoothstep" },
  { id: "eCS261-CS325", source: "CS261", target: "CS325", type: "smoothstep" },
  { id: "eCS225-CS325", source: "CS225", target: "CS325", type: "smoothstep" },
  { id: "eCS271-CS344", source: "CS271", target: "CS344", type: "smoothstep" },
  { id: "eCS261-CS344", source: "CS261", target: "CS344", type: "smoothstep" },
  { id: "eCS271-CS372", source: "CS271", target: "CS372", type: "smoothstep" },
  { id: "eCS261-CS372", source: "CS261", target: "CS372", type: "smoothstep" },
  { id: "eCS225-CS381", source: "CS225", target: "CS381", type: "smoothstep" },
  { id: "eCS261-CS381", source: "CS261", target: "CS381", type: "smoothstep" },
  { id: "eCS261-CS361", source: "CS261", target: "CS361", type: "smoothstep" },
  { id: "eCS261-CS362", source: "CS261", target: "CS362", type: "smoothstep" },
  { id: "eCS261-CS427", source: "CS261", target: "CS427", type: "smoothstep" },
  { id: "eCS261-CS450", source: "CS261", target: "CS450", type: "smoothstep" },
  { id: "eCS261-CS475", source: "CS261", target: "CS475", type: "smoothstep" },
  { id: "eCS290-CS493", source: "CS290", target: "CS493", type: "smoothstep" },
  { id: "eCS340-CS493", source: "CS340", target: "CS493", type: "smoothstep" },
  { id: "eCS372-CS493", source: "CS372", target: "CS493", type: "smoothstep" },
  { id: "eCS340-CS373", source: "CS340", target: "CS373", type: "smoothstep" },
  { id: "eCS344-CS373", source: "CS344", target: "CS373", type: "smoothstep" },
  { id: "eCS372-CS373", source: "CS372", target: "CS373", type: "smoothstep" },
  { id: "eCS344-CS370", source: "CS344", target: "CS370", type: "smoothstep" },
  { id: "eCS344-CS492", source: "CS344", target: "CS492", type: "smoothstep" },
  { id: "eCS344-CS444", source: "CS344", target: "CS444", type: "smoothstep" },
  { id: "eCS271-CS444", source: "CS271", target: "CS444", type: "smoothstep" },
  { id: "eCS372-CS478", source: "CS372", target: "CS478", type: "smoothstep" },
  { id: "eCS344-CS467", source: "CS344", target: "CS467", type: "smoothstep" },
  { id: "eCS361-CS467", source: "CS361", target: "CS467", type: "smoothstep" },
  { id: "eCS362-CS467", source: "CS362", target: "CS467", type: "smoothstep" },
  { id: "eCS261-CS464", source: "CS261", target: "CS464", type: "smoothstep" },
  { id: "eCS361-CS464", source: "CS361", target: "CS464", type: "smoothstep" },
  { id: "eCS344-CS477", source: "CS344", target: "CS477", type: "smoothstep" },
  { id: "eCS370-CS477", source: "CS370", target: "CS477", type: "smoothstep" },
];
